name: powertop-robertliu
base: core24
summary: diagnose issues with power consumption and management
description: |
 PowerTOP is a Linux tool to diagnose issues with power consumption and
 power management. In addition to being a diagnostic tool, PowerTOP also
 has an interactive mode you can use to experiment with various power
 management settings, for cases where the Linux distribution has not
 enabled those settings.
 .
 PowerTOP reports which components in the system are most likely to blame
 for higher-than-needed power consumption, ranging from software
 applications to active components in the system. Detailed screens are
 available for CPU C and P states, device activity, and software activity.
 .
 Notice! Connect all interfaces before using this snap. To get everything
 working, do consider using devmode instead of strict confinement.

grade: stable
confinement: strict
platforms:
    amd64:
        build-on: [amd64]
        build-for: amd64
adopt-info: powertop

apps:
    powertop:
        command: usr/sbin/powertop
        completer: usr/share/bash-completion/completions/powertop
        plugs:
            - cpu-control
            - hardware-observe
            - home
            - kernel-module-observe
            - netlink-audit
            - power-control
            - raw-usb
            - system-observe
            - system-trace

parts:
  powertop:
    # See 'snapcraft plugins'
    plugin: autotools
    source: https://github.com/fenrus75/powertop.git
    #source-depth: 1 ## need full history to get version string
    source-type: git
    autotools-configure-parameters:
        - --prefix=/usr
    override-build: |
        craftctl set version="$(git describe --tags --always --dirty)"
        sed -i 's/^AM_GNU_GETTEXT_REQUIRE_VERSION/AM_GNU_GETTEXT_VERSION/g' configure.ac
        craftctl default
        # update completion
        sed -E -i 's/"\$1"/"powertop"/g;s/^(complete .*) powertop$/\1 powertop-robertliu.powertop/g' \
          $CRAFT_PART_INSTALL/usr/share/bash-completion/completions/powertop
    stage-packages:
        - libpci3
        - libtracefs1
        - libtraceevent1

build-packages:
    - build-essential
    - libpci-dev
    - libnl-3-dev
    - libnl-genl-3-dev
    - gettext
    - libgettextpo-dev
    - autopoint
    - libncurses5-dev
    - libncursesw5-dev
    - libtool-bin
    - dh-autoreconf
    - autoconf-archive
    - pkg-config
    - libtracefs-dev
    - libtraceevent-dev

layout:
    /etc/init.d:
        bind: $SNAP_DATA
    /var/cache/powertop:
        bind: $SNAP_DATA
